# Generated by Django 4.1 on 2022-09-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Patient id as user'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='appointment id')),
                ('schedule_id', models.IntegerField(blank=True, null=True)),
                ('doctor_id', models.IntegerField()),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('appointment_status', models.BooleanField(default=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('doctor_comment', models.TextField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to='patient.patient')),
            ],
        ),
    ]
