# Generated by Django 4.1 on 2022-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_pid_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
